print('Vamos mostrar agora os tipos de cada valor digitado por você')
valor = str(input('Digite um valor: '))
print('O valor primitivo é: ', type(valor))
print('É apenas espaços? ', valor.isspace())
print('É um numero? ', valor.isnumeric())
print('É alfanumerico? ', valor.isalnum())
print('Está em maiuscula? ', valor.isupper())
print('Está em minuscula? ', valor.islower())
print('Está capitalizada? ', valor.istitle())
